version: '3.4'
# description: 'Pastebin alternative'
# icon-url: 'https://i.imgur.com/1Zdh3HR.png'

services:
  lenpaste:
    image: ghcr.io/lcomrade/lenpaste:1.3.1
    ports:
      - '21080:80'
    volumes:
      - '/docker_data/${COMPOSE_PROJECT_NAME}/data:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
