version: '3'
# description: 'Self-hosted YouTube downloader'
# logo: 'https://github.com/meeb/tubesync/blob/main/tubesync/common/static/images/tubesync.png?raw=true'

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - 6581:8081
    volumes:
      - /media/KING128W/media/yt-downloadss:/downloads
